sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t haoly/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true haoly/react-test npm test -- --coverage

after_sucess:
  - docker build -t 142122/complex-client ./client
  - docker build -t 142122/complex-nginx ./nginx
  - docker build -t 142122/complex-server ./server
  - docker build -t 142122/complex-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push 142122/complex-client
  - docker push 142122/complex-nginx
  - docker push 142122/complex-server
  - docker push 142122/complex-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-west-1-427205730437
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

