sudo: required
services:
  - docker

before_install:
  - docker build -t haoly/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run haoly/react-test npm test -- --coverage

after_sucess:
  - docker build -t haoly/complex-client ./client
  - docker build -t haoly/complex-nginx ./nginx
  - docker build -t haoly/complex-server ./server
  - docker build -t haoly/complex-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push haoly/complex-client
  - docker push haoly/complex-nginx
  - docker push haoly/complex-server
  - docker push haoly/complex-worker

